name: Xcode - Build and Analyze

on:
  workflow_dispatch:
jobs:
  iOS:
    name: Unit Tests
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.5,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          set -o pipefail
          xcodebuild build \
          -scheme iOSGitHubActions \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
          | xcpretty
    env:
      destination: ${{ matrix.destination }}
